from compas_tno.plotters import TNOPlotter

paths = ['/Users/mricardo/compas_dev/me/compl_energy/assym/arch/arch/img/fig-0.png', '/Users/mricardo/compas_dev/me/compl_energy/assym/arch/arch/img/fig-1.png', '/Users/mricardo/compas_dev/me/compl_energy/assym/arch/arch/img/fig-2.png', '/Users/mricardo/compas_dev/me/compl_energy/assym/arch/arch/img/fig-3.png', '/Users/mricardo/compas_dev/me/compl_energy/assym/arch/arch/img/fig-4.png', '/Users/mricardo/compas_dev/me/compl_energy/assym/arch/arch/img/fig-5.png', '/Users/mricardo/compas_dev/me/compl_energy/assym/arch/arch/img/fig-6.png', '/Users/mricardo/compas_dev/me/compl_energy/assym/arch/arch/img/fig-7.png', '/Users/mricardo/compas_dev/me/compl_energy/assym/arch/arch/img/fig-8.png', '/Users/mricardo/compas_dev/me/compl_energy/assym/arch/arch/img/fig-9.png', '/Users/mricardo/compas_dev/me/compl_energy/assym/arch/arch/img/fig-10.png', '/Users/mricardo/compas_dev/me/compl_energy/assym/arch/arch/img/fig-11.png', '/Users/mricardo/compas_dev/me/compl_energy/assym/arch/arch/img/fig-12.png', '/Users/mricardo/compas_dev/me/compl_energy/assym/arch/arch/img/fig-13.png', '/Users/mricardo/compas_dev/me/compl_energy/assym/arch/arch/img/fig-14.png', '/Users/mricardo/compas_dev/me/compl_energy/assym/arch/arch/img/fig-15.png', '/Users/mricardo/compas_dev/me/compl_energy/assym/arch/arch/img/fig-16.png', '/Users/mricardo/compas_dev/me/compl_energy/assym/arch/arch/img/fig-17.png', '/Users/mricardo/compas_dev/me/compl_energy/assym/arch/arch/img/fig-18.png', '/Users/mricardo/compas_dev/me/compl_energy/assym/arch/arch/img/fig-19.png', '/Users/mricardo/compas_dev/me/compl_energy/assym/arch/arch/img/fig-20.png', '/Users/mricardo/compas_dev/me/compl_energy/assym/arch/arch/img/fig-21.png', '/Users/mricardo/compas_dev/me/compl_energy/assym/arch/arch/img/fig-22.png', '/Users/mricardo/compas_dev/me/compl_energy/assym/arch/arch/img/fig-23.png', '/Users/mricardo/compas_dev/me/compl_energy/assym/arch/arch/img/fig-24.png', '/Users/mricardo/compas_dev/me/compl_energy/assym/arch/arch/img/fig-25.png', '/Users/mricardo/compas_dev/me/compl_energy/assym/arch/arch/img/fig-26.png', '/Users/mricardo/compas_dev/me/compl_energy/assym/arch/arch/img/fig-27.png', '/Users/mricardo/compas_dev/me/compl_energy/assym/arch/arch/img/fig-28.png', '/Users/mricardo/compas_dev/me/compl_energy/assym/arch/arch/img/fig-29.png', '/Users/mricardo/compas_dev/me/compl_energy/assym/arch/arch/img/fig-30.png', '/Users/mricardo/compas_dev/me/compl_energy/assym/arch/arch/img/fig-31.png', '/Users/mricardo/compas_dev/me/compl_energy/assym/arch/arch/img/fig-32.png', '/Users/mricardo/compas_dev/me/compl_energy/assym/arch/arch/img/fig-33.png', '/Users/mricardo/compas_dev/me/compl_energy/assym/arch/arch/img/fig-34.png', '/Users/mricardo/compas_dev/me/compl_energy/assym/arch/arch/img/fig-35.png']

save = '/Users/mricardo/compas_dev/me/compl_energy/assym/arch/arch/img/gif.gif'
plotter = TNOPlotter()
plotter.make_gif(paths, save, 20)

# images = []
# recording = '/Users/mricardo/compas_dev/me/compl_energy/assym/arch/arch/img/gif.gif'
# for path in paths:
#     images.append(Image.open(path))

# images[0].save(recording, save_all=True, append_images=images[1:], optimize=False, duration=10 * 1000, loop=0)

